### ISSUE TITLE
Add some resources for learning Generics

### ISSUE THREAD

**Issue by MangoIV** [tweag/awesome-learning-haskell#12]
**Is your feature request related to a problem? Please describe.**

I think given that generic programming is getting more popular it would be neat to have some resources to learn generics. (and generics-sop for that matter)

It would also be neat to not only have some resources for generics-sop but also for haskell generics...

**Additional context**
- I'm aware of this https://github.com/srid/generics-sop-examples/blob/master/doc/draft.md but it's still a draft and I don't know when it will be officially published
- and of this https://www.youtube.com/watch?v=pwnrfREbhWY

but I don't think I'm proficient enough to tell whether those are considered good resources (although I gotta say that they helped me learning)

**Comment by marcosh** [comment]
thanks @MangoIV for the suggestion! Having some material regarding generics definitely makes sense. I'll take a look at the material and add something

**Comment by marcosh** [comment]
I added a new section on [generic-programming](https://github.com/tweag/awesome-learning-haskell#generic-programming).

Thanks for the suggestion!

**Comment by MangoIV** [comment]
Thank you for reacting and implementing so quick, I think it will be a great help!
